# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fa595eaee1517f990e3cfc6961bd75a96fe73ed9c9d3c95f633fdd92aa6f9b4ff0f87a9d390777d1fb935f99d462ea93c1fecfaba0e5f3e63b2b2682de8410e

test:
  secret_key_base: 559c5b71cf811fd2cc65f96fce16312978b3570ca8898091253ecbb303b175d591dc51643f6fbba2fd843a8f391c0a842238dce4013e1da7c38267feb3a61de8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
